# Generated by Django 2.1.15 on 2022-05-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('line', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('booking_date', models.CharField(max_length=32)),
                ('star', models.CharField(max_length=32)),
            ],
        ),
    ]
