# Generated by Django 2.1.15 on 2022-06-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobAnnounceDate', models.CharField(max_length=32)),
                ('jobTitles', models.CharField(max_length=1000)),
                ('jobCompanyName', models.CharField(max_length=32)),
                ('jobCompanyUrl', models.CharField(max_length=32)),
                ('jobCompanyIndustry', models.CharField(max_length=32)),
                ('jobContent', models.CharField(max_length=100000)),
                ('jobCategory', models.CharField(max_length=100)),
                ('jobSalary', models.CharField(max_length=32)),
                ('jobLocation', models.CharField(max_length=32)),
                ('jobRqYear', models.CharField(max_length=32)),
                ('jobRqEducation', models.CharField(max_length=32)),
                ('jobRqDepartment', models.CharField(max_length=32)),
                ('jobSpecialty', models.CharField(max_length=32)),
                ('jobOthers', models.CharField(max_length=1000000)),
                ('jobDetailUrl', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
