# Generated by Django 2.1.15 on 2022-06-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220604_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='jobAnnounceDate',
            field=models.CharField(max_length=32),
        ),
    ]
