# Generated by Django 3.2.13 on 2022-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220604_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jiebaCut',
            field=models.CharField(max_length=1000000, null=True, verbose_name='職缺斷詞'),
        ),
    ]
