# Generated by Django 3.2.13 on 2022-06-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jobs_jiebacut'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobType',
            field=models.CharField(max_length=100, null=True, verbose_name='職缺屬性'),
        ),
    ]
