# Generated by Django 3.2.13 on 2022-06-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jobs_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobApplyNums',
            field=models.CharField(max_length=100, null=True, verbose_name='應徵人數'),
        ),
    ]
